name: CI Pipeline

on: 
  push:
    branches:
      - main

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      # Step 4: Run DVC pipeline
      - name: Run DVC pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          source venv/bin/activate
          dvc repro

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t apoorv2690/waterprediction .

      # Step 7: Push Docker image
      - name: Push Docker image
        run: |
          docker push apoorv2690/waterprediction



# name: CI Pipeline

# on: 
#   push:
#     branches:
#       - main

# jobs:
#   project-testing:
#     runs-on: ubuntu-latest
#     steps:
#       # Step 1: Checkout the code
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Set up Python environment
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with: 
#           python-version: '3.10'

#       # Step 3: Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install dvc

#       # Step 4: Run DVC pipeline
#       - name: Run DVC pipeline
#         env:
#           DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
#         run: |
#           source venv/bin/activate
#           dvc repro
#       - name: log in to dockerhub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME}}
#           password: ${{secrets.DOCKERS_TOKEN}}

#       - name: Build docker image
#         if: ${{ success()}}
#         run: |
#           docker build -t apoorv2690/water_potability_predicition .

#       - name: push docker image
#         if: ${{ success()}}
#         run: |
#           docker push apoorv2690/waterprediction