name: CI Pipeline

on: 
  push:
    branches:
      - main

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      # Step 4: Run DVC pipeline
      - name: Run DVC pipeline
        env:
          DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          source venv/bin/activate
          dvc repro


# name: CI pipeline

# on: push

# jobs:
#   project-testing:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3


#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with: 
#           python-version: '3.10'

#       - name: Install dependencies
#         run:
#           pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install dvc

#       - name: Run DVC pipeline
#         run:
#           dvc repro 
       